# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 1048576);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20111115184056");
user_pref("browser.startup.homepage_override.mstone", "rv:8.0");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 6);
user_pref("extensions.enabledAddons", "langpack-es-MX@firefox.mozilla.org:8.0,langpack-en-ZA@firefox.mozilla.org:8.0,langpack-es-ES@firefox.mozilla.org:8.0,langpack-es-CL@firefox.mozilla.org:8.0,langpack-es-AR@firefox.mozilla.org:8.0,langpack-en-GB@firefox.mozilla.org:8.0,{972ce4c6-7e08-4474-a285-3208198ce6fd}:8.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"langpack-es-MX@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-8.0/extensions/langpack-es-MX@firefox.mozilla.org.xpi\",\"mtime\":1321398360000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-8.0/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1321398358000},\"langpack-es-ES@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-8.0/extensions/langpack-es-ES@firefox.mozilla.org.xpi\",\"mtime\":1321398359000},\"langpack-es-CL@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-8.0/extensions/langpack-es-CL@firefox.mozilla.org.xpi\",\"mtime\":1321398359000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox-8.0/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1328746825000},\"langpack-es-AR@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-8.0/extensions/langpack-es-AR@firefox.mozilla.org.xpi\",\"mtime\":1321398359000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-8.0/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1321398358000}}}]");
user_pref("extensions.lastAppVersion", "8.0");
user_pref("extensions.lastPlatformVersion", "8.0");
user_pref("extensions.pendingOperations", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 31150);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.disable_button.openDeviceManager", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1332680536);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
